image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: prashanthdhanasekar/smic
  TAG: v2

stages:
  - build
  - deploy

build:
  stage: build

  tags:
    - docker

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  script:
    - docker build -t $IMAGE_NAME:$TAG .
    - docker push $IMAGE_NAME:$TAG

  only:
    - master


deploy:
  stage: deploy

  tags:
    - privileged

  image: alpine:latest

  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        docker pull $IMAGE_NAME:$TAG &&
        docker stop smic || true &&
        docker rm smic || true &&
        docker run -d \
          --name smic \
          --restart unless-stopped \
          --env-file /opt/smic/.env \
          -p 5000:5000 \
          $IMAGE_NAME:$TAG
      "

  only:
    - master